/* THIS FILE IS AUTOGENERATED DO NOT MODIFY IT DIRECTLY */
import "dotenv/config.js";
declare const appRouter: import("@scinorandex/rpscin").RouterT<"/", {}, import("@scinorandex/rpscin/dist/RouteParameters.js").Overwrite<{
    "/user": import("@scinorandex/rpscin").RouterT<"/user", Omit<{}, keyof import("@scinorandex/rpscin/dist/RouteParameters.js").RouteParameters<SubroutedAt>>, {}, {
        "/login": {
            post: import("@scinorandex/erpc").FinalizedHandler<{
                success: boolean;
            }, {
                username: string;
                password: string;
            }, Omit<Omit<{}, keyof import("@scinorandex/rpscin/dist/RouteParameters.js").RouteParameters<SubroutedAt>>, never>, any>;
        };
        "/register": {
            post: import("@scinorandex/erpc").FinalizedHandler<{
                success: boolean;
            }, {
                username: string;
                password: string;
            }, Omit<Omit<{}, keyof import("@scinorandex/rpscin/dist/RouteParameters.js").RouteParameters<SubroutedAt>>, never>, any>;
        };
    }>;
}, {}>, {
    "/status": {
        get: import("@scinorandex/erpc").FinalizedHandler<{
            status: string;
            time: number;
            timePH: string;
        }, any, Omit<{}, never>, any>;
        ws: import("@scinorandex/erpc").FinalizedHandler<{
            ping: {
                date: number;
            };
            newLogin: {
                username: string;
            };
        }, {}, Omit<{}, never>, {}>;
    };
    "/broadcast": {
        post: import("@scinorandex/erpc").FinalizedHandler<{}, {
            username: string;
        }, Omit<{}, never>, any>;
    };
    "/graphql": {
        post: import("@scinorandex/erpc").FinalizedHandler<any, {
            query: string;
            variables: {};
        }, Omit<{}, never>, any>;
    };
}>;
export type ExportedApi = typeof appRouter;
export {};
